# 指定运行环境
language: node_js

node_js:
  - lts/*

jobs:
  include:
    - name: "Push Compile"
      if: type = push AND branch = develop
      install: yarn install
      before_script:
        - export TZ='Asia/Shanghai'
        - rm -rf dist
        - rm -rf examples/dist
      script:
        - yarn dev
        - yarn build
      after_success:
        - git config --global user.name "Deployment Bot"
        - git config --global user.email "deploy@travis-ci.org"
        - git add -A
        - "git commit -m 'build: Travis CI automatic compilation'"
        - git push "https://juzi214032:${GITHUB_TOKEN}@github.com/TaleLin/lin-ui" HEAD:develop
    - name: "Check Compile"
      if: type = pull_request OR (type = push AND branch = master)
      before_install: export TZ='Asia/Shanghai'
      install: yarn install
      script:
        - yarn dev
        - yarn build
